[book]
authors = ["Neloreck"]
language = "en"
multilingual = false
src = "src"
title = "Xray forge book"

[output.html]
git-repository-url = "https://github.com/xray-forge/stalker-xrf-book"
site-url = "/stalker-xrf-book/"
